### ISSUE TITLE
Loading the chapter file

### ISSUE THREAD

**Issue by archiif** [shinchiro/mpv-createchapter#2]
Is there any easy way of loading back the dumped XML file with mpv?

**Comment by shinchiro** [comment]
Not in my knowledge. Better ask on irc or mpv's tracker to be sure

**Comment by calestyo** [comment]
JFTR: see e.g. https://github.com/mar04/chapters_for_mpv which supports loading and writing (and more). But this is just one of several such tools that I've found (e.g. https://github.com/dyphire/mpv-scripts has one too, but I haven't looked closer at that yet)
